# Github Feature Request Issue Template
# Visit https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

name: Feature Request
description: Request any feature to enhance this app for everyone
title: 'Feature: '
labels: ['feature', 'enhance', 'concept', 'request']
assignees:
  - nyomansunima
body:
  - type: markdown
    attributes:
      value: |
        Hey, thanks to take your time to filling out this feature request. 
        Will be great if we can improve this application together
  - type: input
    id: feature-name
    attributes:
      label: Feature Name
      description: Tell me about what feature do you want in this application
      placeholder: Biometric Login
  - type: textarea
    attributes:
      label: Describe feature
      description: Please tell me the detail idea of feature you wish about!
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Where should implement
      description: Please give me some brief in which platform should you want to implement this kind of feature. You can select more than one
      options:
        - label: Mobile
        - label: Web
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
